version: '3.5'

services:
  # Web app
  panda_retail_app:
    container_name: panda-retail-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
    links:
      - panda_retail_db
    depends_on:
      - panda_retail_db
    networks:
      - panda_retail

  # MongoDb database
  panda_retail_db:
    container_name: panda-retail-db
    logging:
      driver: 'none'
    image: mongo:latest
    command: mongod --port 27040
    ports:
      - 27040:27040
    volumes:
      - 'panda_retail_data:/data/db'
    networks:
      - panda_retail

  # Server
  nginx:
    container_name: panda-retail-nginx
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - panda_retail_app
    networks:
      - panda_retail

networks:
  panda_retail:
    name: panda_retail_network

volumes:
   panda_retail_data:
